hi link markdownBold Identifier
hi link markdownCodeDelimiter Identifier
hi link markdownHeadingDelimiter PreProc
hi link markdownId Identifier
hi link markdownIdDeclaration Identifier
hi link markdownIdDelimiter Identifier
hi link markdownItalic Identifier
hi link markdownLinkDelimiter Identifier
hi link markdownLinkText Identifier
hi link markdownLinkTextDelimiter Identifier
